from __future__ import annotations

import json
import os
import sys
import tempfile
import unittest
from pathlib import Path
from unittest.mock import patch

REPO_ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO_ROOT / "scripts"))

import verify_protocol_codegen as codegen
import verify_protocol_upstream as upstream


class CodegenRuntimeTests(unittest.TestCase):
    def test_codegen_environment_rejects_case_variant_package_manager_config(
        self,
    ) -> None:
        with (
            tempfile.TemporaryDirectory() as directory,
            patch.dict(
                os.environ,
                {
                    "npm_config_registry": "https://attacker.invalid/",
                    "PnPm_HoMe": "/attacker",
                    "node_options": "--require=/attacker.js",
                },
                clear=False,
            ),
        ):
            env = codegen._clean_environment(Path(directory))
        self.assertNotIn("npm_config_registry", env)
        self.assertNotIn("PnPm_HoMe", env)
        self.assertNotIn("node_options", env)
        self.assertEqual(
            "https://registry.npmjs.org/",
            env["NPM_CONFIG_REGISTRY"],
        )

    def test_prepare_rejects_source_digest_before_install(self) -> None:
        lock = upstream.load_lock()
        with tempfile.TemporaryDirectory() as directory:
            workspace = Path(directory) / "prepared"
            with self.assertRaisesRegex(
                codegen.CodegenVerificationError,
                "digest differs during prepare",
            ):
                codegen.prepare_workspace(
                    lock,
                    workspace,
                    fetch=lambda _url: b"mutated upstream source",
                )

    def test_runtime_version_mismatch_fails_closed(self) -> None:
        with self.assertRaisesRegex(
            codegen.CodegenVerificationError,
            "node version differs",
        ):
            codegen.require_version(
                "node",
                actual="v24.13.0",
                expected="24.14.0",
                prefix="v",
            )

    def test_runtime_version_accepts_only_exact_normalized_value(self) -> None:
        codegen.require_version(
            "node",
            actual="v24.14.0\n",
            expected="24.14.0",
            prefix="v",
        )
        with self.assertRaisesRegex(
            codegen.CodegenVerificationError,
            "pnpm version differs",
        ):
            codegen.require_version(
                "pnpm",
                actual="10.33.0 extra",
                expected="10.33.0",
            )

    def test_installed_generator_package_version_mismatch_fails(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            package_root = Path(directory)
            for name, version in {
                "cddl": "0.20.1",
                "cddl2py": "0.2.2",
                "cddl2ts": "0.9.1",
            }.items():
                path = package_root / "node_modules" / name
                path.mkdir(parents=True)
                (path / "package.json").write_text(
                    json.dumps({"name": name, "version": version}),
                    encoding="utf-8",
                )
            (package_root / "node_modules/cddl2ts/package.json").write_text(
                json.dumps({"name": "cddl2ts", "version": "0.9.2"}),
                encoding="utf-8",
            )
            with self.assertRaisesRegex(
                codegen.CodegenVerificationError,
                "cddl2ts package version differs",
            ):
                codegen.verify_installed_package_versions(
                    package_root,
                    {
                        "cddl": "0.20.1",
                        "cddl2py": "0.2.2",
                        "cddl2ts": "0.9.1",
                    },
                )


class CodegenBindingTests(unittest.TestCase):
    def test_three_way_binding_comparison_accepts_identical_bytes(self) -> None:
        digest = codegen.verify_binding_bytes(
            "typescript",
            generated=b"same\n",
            upstream=b"same\n",
            vendored=b"same\n",
        )
        self.assertEqual(
            "a6328afc76e9db71da297ebff4b0d3e7a7eb3b01d917c05a6573fef121b6ecb6",
            digest,
        )

    def test_three_way_binding_comparison_rejects_generated_drift(self) -> None:
        with self.assertRaisesRegex(
            codegen.CodegenVerificationError,
            "generated bytes differ from locked upstream",
        ):
            codegen.verify_binding_bytes(
                "python",
                generated=b"mutated\n",
                upstream=b"locked\n",
                vendored=b"locked\n",
            )

    def test_three_way_binding_comparison_rejects_vendored_drift(self) -> None:
        with self.assertRaisesRegex(
            codegen.CodegenVerificationError,
            "vendored bytes differ from locked upstream",
        ):
            codegen.verify_binding_bytes(
                "python",
                generated=b"locked\n",
                upstream=b"locked\n",
                vendored=b"mutated\n",
            )


if __name__ == "__main__":
    unittest.main()
